// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.se.test;

import com.se.test.Lol;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Lol_Roo_Jpa_Entity {
    
    declare @type: Lol: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Lol.id;
    
    @Version
    @Column(name = "version")
    private Integer Lol.version;
    
    public Long Lol.getId() {
        return this.id;
    }
    
    public void Lol.setId(Long id) {
        this.id = id;
    }
    
    public Integer Lol.getVersion() {
        return this.version;
    }
    
    public void Lol.setVersion(Integer version) {
        this.version = version;
    }
    
}
