// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.se.test;

import com.se.test.Lol;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Lol_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Lol.entityManager;
    
    public static final List<String> Lol.fieldNames4OrderClauseFilter = java.util.Arrays.asList("");
    
    public static final EntityManager Lol.entityManager() {
        EntityManager em = new Lol().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Lol.countLols() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Lol o", Long.class).getSingleResult();
    }
    
    public static List<Lol> Lol.findAllLols() {
        return entityManager().createQuery("SELECT o FROM Lol o", Lol.class).getResultList();
    }
    
    public static List<Lol> Lol.findAllLols(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Lol o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Lol.class).getResultList();
    }
    
    public static Lol Lol.findLol(Long id) {
        if (id == null) return null;
        return entityManager().find(Lol.class, id);
    }
    
    public static List<Lol> Lol.findLolEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Lol o", Lol.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<Lol> Lol.findLolEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Lol o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Lol.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Lol.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Lol.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Lol attached = Lol.findLol(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Lol.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Lol.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Lol Lol.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Lol merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
