// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.se.test.domain;

import com.se.test.domain.Cus;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Cus_Roo_Jpa_Entity {
    
    declare @type: Cus: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Cus.id;
    
    @Version
    @Column(name = "version")
    private Integer Cus.version;
    
    public Long Cus.getId() {
        return this.id;
    }
    
    public void Cus.setId(Long id) {
        this.id = id;
    }
    
    public Integer Cus.getVersion() {
        return this.version;
    }
    
    public void Cus.setVersion(Integer version) {
        this.version = version;
    }
    
}
