// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.se.test.web;

import com.se.test.domain.Cus;
import com.se.test.web.ApplicationConversionServiceFactoryBean;
import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.core.convert.converter.Converter;
import org.springframework.format.FormatterRegistry;

privileged aspect ApplicationConversionServiceFactoryBean_Roo_ConversionService {
    
    declare @type: ApplicationConversionServiceFactoryBean: @Configurable;
    
    public Converter<Cus, String> ApplicationConversionServiceFactoryBean.getCusToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.se.test.domain.Cus, java.lang.String>() {
            public String convert(Cus cus) {
                return "(no displayable fields)";
            }
        };
    }
    
    public Converter<Long, Cus> ApplicationConversionServiceFactoryBean.getIdToCusConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.se.test.domain.Cus>() {
            public com.se.test.domain.Cus convert(java.lang.Long id) {
                return Cus.findCus(id);
            }
        };
    }
    
    public Converter<String, Cus> ApplicationConversionServiceFactoryBean.getStringToCusConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.se.test.domain.Cus>() {
            public com.se.test.domain.Cus convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Cus.class);
            }
        };
    }
    
    public void ApplicationConversionServiceFactoryBean.installLabelConverters(FormatterRegistry registry) {
        registry.addConverter(getCusToStringConverter());
        registry.addConverter(getIdToCusConverter());
        registry.addConverter(getStringToCusConverter());
    }
    
    public void ApplicationConversionServiceFactoryBean.afterPropertiesSet() {
        super.afterPropertiesSet();
        installLabelConverters(getObject());
    }
    
}
