// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.se.test.web;

import com.se.test.domain.Cus;
import com.se.test.web.CusController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect CusController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String CusController.create(@Valid Cus cus, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, cus);
            return "cuses/create";
        }
        uiModel.asMap().clear();
        cus.persist();
        return "redirect:/cuses/" + encodeUrlPathSegment(cus.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String CusController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Cus());
        return "cuses/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String CusController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("cus", Cus.findCus(id));
        uiModel.addAttribute("itemId", id);
        return "cuses/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String CusController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("cuses", Cus.findCusEntries(firstResult, sizeNo, sortFieldName, sortOrder));
            float nrOfPages = (float) Cus.countCuses() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("cuses", Cus.findAllCuses(sortFieldName, sortOrder));
        }
        return "cuses/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String CusController.update(@Valid Cus cus, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, cus);
            return "cuses/update";
        }
        uiModel.asMap().clear();
        cus.merge();
        return "redirect:/cuses/" + encodeUrlPathSegment(cus.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String CusController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, Cus.findCus(id));
        return "cuses/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String CusController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Cus cus = Cus.findCus(id);
        cus.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/cuses";
    }
    
    void CusController.populateEditForm(Model uiModel, Cus cus) {
        uiModel.addAttribute("cus", cus);
    }
    
    String CusController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
